site_name: Arseny's Cheatsheet
site_url: 'https://arsenyafonin.github.io/cheatsheet/'
docs_dir: markdown
site_dir: docs
site_favicon: 'favicon.ico'

pages:
- Введение: 'index.md'
- Python:
  - Импорт модулей: 'python-import.md'
  - Работа с файлами: 'python-os.md'
  - Анализ данных: 'python-pandas.md'
  - Регулярные выражения: 'python-regex.md'
  - Базовые библиотеки: 'python-utilities.md'
  - Среда: 'python-pipenv.md'
- R:
  - Импорт данных: 'R-data.md'
  - Shiny: 'python-os.md'
- Markdown: 'instructions.md'
- Command Prompt | Bash: 'cmd-bash.md'
- Система:
  - Горячие клавиши: 'shortcuts.md'
- Преднастройка:
    - Atom: 'atom.md'
    - AWS CLI: 'aws-cli.md'
    - Windows 10: 'system.md'

# Documentation and theme
theme: 'material'
theme_dir: 'theme'

# Options
markdown_extensions:
  - admonition
  - toc(permalink=true)
  - codehilite

extra:
  palette:
    primary: 'cyan'
    accent: 'cyan'

extra_css: [extra.css]
