site_name: カンニングペーパー
site_url: 'https://arsenyafonin.github.io/cheatsheet/'
docs_dir: markdown
site_dir: docs

nav:
- Введение: 'index.md'
- Python:
  - Импорт модулей: 'python-import.md'
  - Работа с файлами: 'python-os.md'
  - Анализ данных: 'python-pandas.md'
  - Регулярные выражения: 'python-regex.md'
  - Базовые библиотеки: 'python-utilities.md'
  - Среда: 'python-pipenv.md'
- R:
  - Импорт данных: 'R-data.md'
  - Shiny: 'R-shiny.md'
- Markdown: 'instructions.md'
- Shell: 'cmd-bash.md'
- Система:
  - Горячие клавиши (Windows): 'shortcuts-windows.md'
  - Горячие клавиши (Mac OS): 'shortcuts-mac.md'
  - Настройка системы (Mac OS): 'system-settings.md'
- Приложения:
    - Atom: 'apps-atom.md'
    - AWS CLI: 'apps-aws-cli.md'
    - Google Spreadsheets: 'apps-spreadsheets.md'

# Documentation and theme
theme:
    name: 'material'
    custom_dir: 'theme'
    language: 'ja'
    favicon: 'assets/images/fav.png'
    logo: 'assets/images/icon.png'
    palette:
      primary: 'white'
      accent: 'teal'

extra_css: ['assets/stylesheets/extra.css']

repo_name: 'noideaatall/cheatsheet'
repo_url: 'https://github.com/arsenyafonin/cheatsheet'

# Options
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
