site_name: Arseny's Cheatsheet
site_url: 'https://arsenyafonin.github.io/cheatsheet/'
docs_dir: markdown
site_dir: docs

nav:
- Введение: 'index.md'
- Python:
  - Импорт модулей: 'python-import.md'
  - Работа с файлами: 'python-os.md'
  - Анализ данных: 'python-pandas.md'
  - Регулярные выражения: 'python-regex.md'
  - Базовые библиотеки: 'python-utilities.md'
  - Среда: 'python-pipenv.md'
- R:
  - Импорт данных: 'R-data.md'
  - Shiny: 'R-shiny.md'
- Markdown: 'instructions.md'
- Command Prompt | Bash: 'cmd-bash.md'
- Система:
  - Горячие клавиши (Windows): 'shortcuts-windows.md'
  - Горячие клавиши (Mac OS): 'shortcuts-mac.md'
  - Настройка системы (Mac OS): 'system-settings.md'
- Преднастройка:
    - Atom: 'atom.md'
    - AWS CLI: 'aws-cli.md'
    - Windows 10: 'system.md'

# Documentation and theme
theme:
    name: 'material'
    custom_dir: 'theme/'

# Options
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

extra:
  palette:
    primary: 'cyan'
    accent: 'cyan'

extra_css: [extra.css]
